basePath: /api
definitions:
  contracts.Submission:
    properties:
      gradeID:
        type: integer
      id:
        type: integer
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Activity:
    properties:
      content:
        type: string
      createdAt:
        type: string
      deadline:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      teacherID:
        type: integer
      updatedAt:
        type: string
    type: object
  requests.PublishActivityRequest:
    properties:
      content:
        type: string
      deadline:
        type: string
      teacher_id:
        type: integer
    required:
    - content
    - deadline
    - teacher_id
    type: object
info:
  contact:
    email: fabio.dsilva@al.infnet.edu.br
    name: Fábio Pereira da Silva
  description: Service for managing activities.
  termsOfService: http://swagger.io/terms/
  title: Activities - School Management System
  version: "1.0"
paths:
  /activities/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Activity'
            type: array
      summary: Busca atividades
    post:
      consumes:
      - application/json
      parameters:
      - description: Activity
        in: body
        name: activity
        required: true
        schema:
          $ref: '#/definitions/requests.PublishActivityRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Activity'
      summary: Publica uma nova atividade
  /activities/{id}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Activity'
      summary: Busca uma atividade pela ID
  /activities/{id}/submissions:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/contracts.Submission'
            type: array
      summary: Busca as submissões de uma atividade
swagger: "2.0"
